encoding: "UTF-8"
# 1. SET THE PRIMARY OUTPUT LANGUAGE
lang: zh-tw # Use zh-tw or zh-Hant consistently for the document metadata.

callout-format:
  .major-question:
    title: "é‡å¤§å•é¡Œ"
    icon: "â“ğŸ¤”" # Using a simpler emoji for consistency
    callout-style: default
  .hypothesis: # This class is perfect for your Model/Taxonomy blocks
    title: "å‡èªª"
    icon: "ğŸ§ª"
    callout-style: default
  .exercise-question:
    title: "æ€è€ƒç·´ç¿’"
    icon: "ğŸ‹ğŸ¤”" # Using a simpler emoji for consistency
    callout-style: default
project:
  type: book # å¿…é ˆå­˜åœ¨ï¼Œæ¨™è¨˜ç‚ºæ›¸ç±å°ˆæ¡ˆ
  output-dir: _site
language: _language-zh-hant.yml 
book:
  title: "é“ï¼ç›œæ™ºæ ¼å±€ï¼šAI è³½å±€æ‰‹å†Š"
  author: "å»–æ¼¢é¨°"
  date: "18/08/2025"
  chapters:
    - file: index.zh-hant.md
    - file: notes-mental_fill-in.zh-hant.md
    - file: notes-constructive_fill-in.zh-hant.md
    - file: toc.zh-hant.md         # This page will display the full TOC/Listings
    - part: 01----problematics.zh-hant.md
      chapters:
        - file: 01-01-Turing_Test.zh-hant.md
          id: sec-turing-test
        - file: 01-02-Chinese_Room.zh-hant.md
          id: sec-chinese-room
        - file: 01-03-Symbol_Grounding_Problem.zh-hant.md
          id: sec-symbol-grounding-problem
        - file: 01-04-Frame_Problem.zh-hant.md
          id: sec-frame-problem
        - file: 01-05-Gestalt_Psychology.zh-hant.md
          id: sec-gestalt-psychology
        - file: 01-06-Alignment_Control_Problem.zh-hant.md
          id: sec-alignment-control-problem
        - file: 01-07-Language_Games.zh-hant.md
          id: sec-language-games
    - part: 02----schools_paradigms.zh-hant.md
      chapters:
        - file: 02-01-symbolic_ai.zh-hant.md
          id: sec-symbolic-ai
        - file: 02-02-statistical_ai.zh-hant.md
          id: sec-statistical-ai
        - file: 02-03-neurosymbolic_ai.zh-hant.md
          id: sec-neurosymbolic-ai
        - file: 02-04-agi.zh-hant.md
          id: sec-agi
        - file: 02-05-connectionism.zh-hant.md
          id: sec-connectionism
        - file: 02-06-behaviorism.zh-hant.md
          id: sec-behaviorism
        - file: 02-07-large_language_models.zh-hant.md
          id: sec-large-language-models
    - part: 03----symbolic_ai.zh-hant.md
      chapters:
        - file: 03-01-formal_logic.zh-hant.md
          id: sec-formal-logic
        - file: 03-02-automatic_dialogue_systems.zh-hant.md
          id: sec-automatic-dialogue-systems
        - file: 03-03-expert_systems.zh-hant.md
          id: sec-expert-systems
        - file: 03-04-knowledge_representation.zh-hant.md
          id: sec-knowledge-representation
        - file: 03-05-knowledge_graph.zh-hant.md
          id: sec-knowledge-graph
        - file: 03-06-semantic_web.zh-hant.md
          id: sec-semantic-web
        - file: 03-07-ontology.zh-hant.md
          id: sec-ontology
    - part: 04----statistical_ai.zh-hant.md
      chapters:
        - file: 04-01-probabilistic_association.zh-hant.md
          id: sec-probabilistic-association
        - file: 04-02-llm_chatbots.zh-hant.md
          id: sec-llm-chatbots
        - file: 04-03-neural_networks.zh-hant.md
          id: sec-neural-networks
        - file: 04-04-feature_engineering.zh-hant.md
          id: sec-feature-engineering
        - file: 04-05-machine_learning_models.zh-hant.md
          id: sec-machine-learning-models
        - file: 04-06-llm_webassembly.zh-hant.md
          id: sec-llm-webassembly
        - file: 04-07-vector_space.zh-hant.md
          id: sec-vector-space
    - part: 05----ai_orientations.zh-hant.md
      chapters:
        - file: 05-01-oriented_task.zh-hant.md
          id: sec-oriented-task
        - file: 05-02-oriented_tool.zh-hant.md
          id: sec-oriented-tool
        - file: 05-03-oriented_agent.zh-hant.md
          id: sec-oriented-agent
        - file: 05-04-oriented_collaborative.zh-hant.md
          id: sec-oriented-collaborative
        - file: 05-05-oriented_governance.zh-hant.md
          id: sec-oriented-governance
    - part: 06----analytics_decisions.zh-hant.md
      chapters:
        - file: 06-01-analysis_diagnostic.zh-hant.md
          id: sec-analysis-diagnostic
        - file: 06-02-analysis_predictive.zh-hant.md
          id: sec-analysis-predictive
        - file: 06-03-analysis_prescriptive.zh-hant.md
          id: sec-analysis-prescriptive
        - file: 06-04-analysis_descriptive.zh-hant.md
          id: sec-analysis-descriptive
        - file: 06-05-analysis_generative.zh-hant.md
          id: sec-analysis-generative
        - file: 06-06-decision_making_algorithm.zh-hant.md
          id: sec-decision-making-algorithm
    - part: 07----game_ai.zh-hant.md
      chapters:
        - file: 07-01-ieee_micromouse.zh-hant.md
          id: sec-ieee-micromouse
        - file: 07-02-atari_dqn.zh-hant.md
          id: sec-atari-dqn
        - file: 07-03-alphago.zh-hant.md
          id: sec-alphago
        - file: 07-04-poker_ai.zh-hant.md
          id: sec-poker-ai
        - file: 07-05-openai_five.zh-hant.md
          id: sec-openai-five
        - file: 07-06-werewolf_ai.zh-hant.md
          id: sec-werewolf-ai
        - file: 07-07-battlefield_simulation.zh-hant.md
          id: sec-battlefield-simulation
    - part: 08----embodied_ai.zh-hant.md
      chapters:
        - file: 08-01-robotics_and_physical_actuation.zh-hant.md
          id: sec-robotics-and-physical-actuation
        - file: 08-02-perception_and_environment.zh-hant.md
          id: sec-perception-and-environment
        - file: 08-03-adaptive_robotics.zh-hant.md
          id: sec-adaptive-robotics
        - file: 08-04-human_robot_interaction.zh-hant.md
          id: sec-human-robot-interaction
        - file: 08-05-robot_safety_and_robustness.zh-hant.md
          id: sec-robot-safety-and-robustness
        - file: 08-06-robot_tasks_and_goals.zh-hant.md
          id: sec-robot-tasks-and-goals
    - part: 09----ai_math.zh-hant.md
      chapters:
        - file: 09-01-collaborative_filtering.zh-hant.md
          id: sec-collaborative-filtering
        - file: 09-02-steepest_descent_method.zh-hant.md
          id: sec-steepest-descent-method
        - file: 09-03-bayesian_network.zh-hant.md
          id: sec-bayesian-network
        - file: 09-04-sparse_modeling.zh-hant.md
          id: sec-sparse-modeling
        - file: 09-05-markov_modeling.zh-hant.md
          id: sec-markov-modeling
        - file: 09-06-monte_carlo_tree_search.zh-hant.md
          id: sec-monte-carlo-tree-search
        - file: 09-07-hebb_rule.zh-hant.md
          id: sec-hebb-rule
        - file: 09-08-multi_agent_payoff_matrix.zh-hant.md
          id: sec-multi-agent-payoff-matrix
    - part: 10----ai_engineering.zh-hant.md
      chapters:
        - file: 10-01-API_MCP.zh-hant.md
          id: sec-api-mcp
        - file: 10-02-agent_reliability_evaluation.zh-hant.md
          id: sec-agent-reliability-evaluation
        - file: 10-03-prompt_engineering.zh-hant.md
          id: sec-prompt-engineering
        - file: 10-04-retrieval_augmented_generation.zh-hant.md
          id: sec-retrieval-augmented-generation
        - file: 10-05-context_engineering.zh-hant.md
          id: sec-context-engineering
        - file: 10-06-AI_PM.zh-hant.md
          id: sec-ai-pm
  appendices:
    - file: appendix-action.zh-hant.qmd
      id: app-action
    - file: appendix-brain.zh-hant.md
      id: app-brain
    - file: appendix-cognitive_capacity.zh-hant.md
      id: app-cognitive-capacity
    - file: appendix-MCP_API.zh-hant.md
      id: app-api
    - file: appendix-mindmap.zh-hant.qmd
      id: fig-mindmap
    - file: cover_back.zh-hant.md
      id: sec-cover-back
    - file: glossary.zh-hant.md
      id: sec-book-glossary
    - file: references.zh-hant.qmd
      id: sec-book-references
  sidebar:
    search: true
    style: "docked"
    #style: "floating"
    collapse-level: 1
    section-numbers: true
  page-footer:
    left: |
      ã€Šé“ï¼ç›œæ™ºæ ¼å±€ï¼šAI è³½å±€æ‰‹å†Šã€‹ï¼š (é å°ç‰ˆ)
      Han-Teng Liao
    right: |
      This book was built with <a href="https://quarto.org/">Quarto</a>.
  cover-image: cover.png
  favicon: cover.png
  search: true
  repo-url: https://github.com/hanteng/frmAI/
  repo-actions: [edit]
  downloads: [pdf, epub]
  sharing: [twitter, facebook]

bibliography: references.bib
resources:
  - scripts/toggle.js
  - scripts/toggle.html
  - styles.css
format:
  html:
    lang: zh-Hant  # zh-Hant<-- This sets the <html lang="..."> attribute
    css: styles.css
    toc: true
    toc-depth: 4
    toc-location: right
    toc-title: "ã€œğŸ“–æœ¬é ç« ç¯€ç›®éŒ„ğŸ“‘ã€œ"
    section-title-appendices: "ğŸ”–é™„éŒ„èˆ‡ç­†è¨˜"
    # âœ… æ­£ç¢ºçš„éµå:
    toc-title-document: "ã€œæœ¬é ç« ç¯€ç›®éŒ„ã€œ"
    crossref-nte-prefix: "è¨»é‡‹"
    crossref-nte-title: "è¨»é‡‹"
    crossref-tip-prefix: "æç¤º"
    crossref-tip-title: "æç¤º"
    callout-important-title: "è¦é»"
    number-sections: true # enable right-hand TOC
    number-depth: 4
    custom-elements:
      model:
        text: "æ¨¡å‹"
        prefix: "mod" 
      taxonomy:
        text: "åˆ†é¡"
        prefix: "tax"
    filters:
      - filters/svg-embed.lua
      - filters/list-floats-toc.lua
    mermaid: 
      theme: default       # or 'dark', 'neutral', etc.
      securityLevel: loose # allows links and some HTML
    #include-in-header:
      #- file: scripts/mermaid.min.js upgraded manually docs\site_libs\quarto-diagram
    include-after-body: 
      - file: scripts/toggle.html
      - file: scripts/zoom.html
    clean-urls: false
    theme:
      - cosmo
      - brand
    cover-image: cover.png
    favicon: cover.jpg
#  pdf:
#    toc: true
#    toc-location: before-body    
#    documentclass: scrreprt
#    cover-image: cover.svg
#  epub:
#    cover-image: cover.svg
